[redis]
chunk_size = 10
blocktime_millis = 1000
consumer_group = "log-ingestor"
consumer_id = "log-ingestor"

[redis.url]
url = "redis://127.0.0.1"
port = 6379

[elastic]
api_key = "ZUl6dGVaZ0JEbkl1Njd5RGl2MVc6UUluVTVWZ0FqNDZ2VlQzYkRwRHJzQQ=="
chunk_size = 100

[elastic.url]
url = "http://localhost"
port = 9200
